def add_two(a):
    x = 2
    return a + x

add_two(3)
5

print(x)
Traceback (most recent call last):
    file "<pyshell#5>", line 1,in <module>
    print(x)
NameError: name 'x' is not defined
